services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: felipe.cadavid@udea.edu.co
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  db:
    container_name: AnimePageDB
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 841205
      POSTGRES_DB: AnimePageDB
    ports:
      - "5432:5432"

  anime_page:
    container_name: anime_page_container
    image: your-docker-image-for-anime-page:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/AnimePage
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 841205
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    depends_on:
      - db