services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: felipe.cadavid@udea.edu.co
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  db:
    container_name: AnimePageDB
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 841205
      POSTGRES_DB: AnimePage
    ports:
      - "5432:5432"


